version: '3.8'

services:
  freedom-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
